# Generated by Django 5.0.1 on 2024-01-05 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_last_login_user_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='token',
            field=models.CharField(default=' ', max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='token_renewed',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
